In [1]:
import os
import sys

In [2]:
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)
%load_ext autoreload
%autoreload 2

In [ ]:
from src.data_cleaning.cleaning import run_data_cleaning_pipeline
import pandas as pd

In [25]:
df=pd.read_csv('../data/raw/portfolio_prices.csv', index_col='Date', parse_dates=True)

In [ ]:
prices=df
weights = pd.Series({t: 0.10 for t in prices.columns}) 
#this weights is calculated with weights keeping in mind about the different weights that can be provided e.g - weights=[0.25, 0.15, 0.12, 0.10, 0.08, 0.07, 0.06, 0.05, 0.09, 0.03]
result = run_data_cleaning_pipeline(
    prices,
    weights
)
result

2026-07-28 14:46:23.811 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:2 - ============================================================
2026-07-28 14:46:23.814 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:3 - Phase 2 – Data Cleaning pipeline started
2026-07-28 14:46:23.817 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:4 - ============================================================
2026-07-28 14:46:23.822 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:11 - Input prices: 2514 rows × 10 tickers | 2016-01-04 → 2025-12-31
2026-07-28 14:46:23.825 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:12 - Weights sum: 1.000000 | tickers: ['AAPL', 'MSFT', 'NVDA', 'JPM', 'XOM', 'AMZN', 'META', 'GOOGL', 'TSLA', 'UNH']
2026-07-28 14:46:23.827 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:14 - [1/7] Aligning trading dates (freq='B') ...
2026-07-28 14:46:24.046 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:17 -         2514 → 2608 rows (94 calendar gaps introduced)
2026-07-28 14:46:24.050 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:20 - [2/7] Handling missing values (method='ffill_bfill') ...
2026-07-28 14:46:24.058 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:22 -         Filled 940 missing cell(s)
2026-07-28 14:46:24.062 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:23 - [3/7] Removing stale prices (window=3) ...
2026-07-28 14:46:24.086 | WARNING  | src.data_cleaning.cleaning:run_data_cleaning_pipeline:26 -         Replaced 5 stale cell(s)
2026-07-28 14:46:24.091 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:29 - [4/7] Validating clean prices ...
2026-07-28 14:46:24.103 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:31 -         OK – all prices positive, numeric, DatetimeIndex
2026-07-28 14:46:24.107 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:32 - [5/7] Computing log returns ...
2026-07-28 14:46:24.146 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:34 -         2607 observations | mean=0.000904 | std=0.022578
2026-07-28 14:46:24.150 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:41 - [6/7] Winsorisation skipped
2026-07-28 14:46:24.152 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:42 - [7/7] Building portfolio returns & rolling volatility ...
2026-07-28 14:46:24.165 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:45 -         Portfolio return mean=0.000904 | std=0.014808 | worst day=-14.9116% | best day=11.2955%
2026-07-28 14:46:24.170 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:48 -         Rolling vol (ann.): last=9.42% | mean=20.53% | max=103.79%
2026-07-28 14:46:24.174 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:50 - ============================================================
2026-07-28 14:46:24.181 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:51 - Phase 2 complete | missing_filled=940 | stale_removed=5 | winsorised=0
2026-07-28 14:46:24.185 | INFO     | src.data_cleaning.cleaning:run_data_cleaning_pipeline:52 - ============================================================

CleanedDataResult(clean_prices=                  AAPL        MSFT        NVDA         JPM         XOM  \
2016-01-04   23.709105   47.770718    0.788626   48.184071   49.319611
2016-01-05   23.114967   47.988655    0.801295   48.267376   49.739857
2016-01-06   22.662615   47.116932    0.768161   47.570591   49.325985
2016-01-07   21.706150   45.478069    0.737707   45.646870   48.536476
2016-01-08   21.820921   45.617558    0.721872   44.624424   47.555935
...                ...         ...         ...         ...         ...
2025-12-25  273.302216  485.856323  188.380234  324.561249  117.632187
2025-12-26  272.892975  485.547729  190.297897  323.318878  117.523659
2025-12-29  273.252350  484.940430  187.990707  319.217133  118.924744
2025-12-30  272.573578  485.318756  187.311539  318.891754  119.378616
2025-12-31  271.355835  481.475861  186.272812  317.708557  118.737274

                  AMZN        META       GOOGL        TSLA         UNH
2016-01-04   31.849501  101.330170   37.638252   14.894000   97.893661
2016-01-05   31.689501  101.835724   37.741837   14.895333   98.078636
2016-01-06   31.632500  102.073631   37.632797   14.602667   97.078346
2016-01-07   30.396999   97.067596   36.724358   14.376667   94.220337
2016-01-08   30.352501   96.482735   36.224297   14.066667   92.598045
...                ...         ...         ...         ...         ...
2025-12-25  232.380005  666.361389  313.681671  485.399994  323.206940
2025-12-26  232.520004  662.108887  313.102478  475.190002  327.400208
2025-12-29  232.070007  657.517151  313.152405  459.640015  324.548798
2025-12-30  232.529999  664.764221  313.442017  454.429993  327.725830
2025-12-31  230.820007  658.914673  312.593109  449.720001  325.703186

[2608 rows x 10 columns], clean_returns=                AAPL      MSFT      NVDA       JPM       XOM      AMZN  \
2016-01-05 -0.025379  0.004552  0.015936  0.001727  0.008485 -0.005036
2016-01-06 -0.019764 -0.018332 -0.042229 -0.014541 -0.008356 -0.001800
2016-01-07 -0.043121 -0.035402 -0.040452 -0.041280 -0.016135 -0.039841
2016-01-08  0.005274  0.003062 -0.021700 -0.022654 -0.020409 -0.001465
2016-01-11  0.016063 -0.000574  0.001686 -0.001529 -0.013479  0.017456
...              ...       ...       ...       ...       ...       ...
2025-12-25  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2025-12-26 -0.001499 -0.000635  0.010128 -0.003835 -0.000923  0.000602
2025-12-29  0.001316 -0.001252 -0.012198 -0.012768  0.011851 -0.001937
2025-12-30 -0.002487  0.000780 -0.003619 -0.001020  0.003809  0.001980
2025-12-31 -0.004478 -0.007950 -0.005561 -0.003717 -0.005387 -0.007381

                META     GOOGL      TSLA       UNH
2016-01-05  0.004977  0.002748  0.000090  0.001888
2016-01-06  0.002333 -0.002893 -0.019844 -0.010251
2016-01-07 -0.050287 -0.024436 -0.015598 -0.029882
2016-01-08 -0.006044 -0.013710 -0.021799 -0.017368
2016-01-11  0.001848  0.002951 -0.015041 -0.005279
...              ...       ...       ...       ...
2025-12-25  0.000000  0.000000  0.000000  0.000000
2025-12-26 -0.006402 -0.001848 -0.021259  0.012891
2025-12-29 -0.006959  0.000159 -0.033271 -0.008747
2025-12-30  0.010962  0.000924 -0.011400  0.009741
2025-12-31 -0.008838 -0.002712 -0.010419 -0.006191

[2607 rows x 10 columns], portfolio_returns=2016-01-05    0.000999
2016-01-06   -0.013568
2016-01-07   -0.033643
2016-01-08   -0.011681
2016-01-11    0.000410
                ...
2025-12-25    0.000000
2025-12-26   -0.001278
2025-12-29   -0.006381
2025-12-30    0.000967
2025-12-31   -0.006263
Freq: B, Name: portfolio_returns, Length: 2607, dtype: float64, rolling_volatility=2016-01-05         NaN
2016-01-06         NaN
2016-01-07         NaN
2016-01-08         NaN
2016-01-11         NaN
                ...
2025-12-25    0.090902
2025-12-26    0.091280
2025-12-29    0.092246
2025-12-30    0.091118
2025-12-31    0.094189
Freq: B, Name: rolling_volatility, Length: 2607, dtype: float64, weights=AAPL     0.1
MSFT     0.1
NVDA     0.1
JPM      0.1
XOM      0.1
AMZN     0.1
META     0.1
GOOGL    0.1
TSLA     0.1
UNH      0.1
dtype: float64, n_missing_filled=940, n_stale_removed=5, n_returns_winsorized=0, metadata={'align_dates': True, 'missing_method': 'ffill_bfill', 'stale_window': 3, 'apply_winsorize': False, 'vol_window': 21, 'n_assets': 10, 'n_dates': 2608, 'return_start': '2016-01-05', 'return_end': '2025-12-31'})

#### Cleaned Portfolio Prices

In [27]:
result.clean_prices

,AAPL,MSFT,NVDA,JPM,XOM,AMZN,META,GOOGL,TSLA,UNH
2016-01-04,23.709105,47.770718,0.788626,48.184071,49.319611,31.849501,101.330170,37.638252,14.894000,97.893661
2016-01-05,23.114967,47.988655,0.801295,48.267376,49.739857,31.689501,101.835724,37.741837,14.895333,98.078636
2016-01-06,22.662615,47.116932,0.768161,47.570591,49.325985,31.632500,102.073631,37.632797,14.602667,97.078346
2016-01-07,21.706150,45.478069,0.737707,45.646870,48.536476,30.396999,97.067596,36.724358,14.376667,94.220337
2016-01-08,21.820921,45.617558,0.721872,44.624424,47.555935,30.352501,96.482735,36.224297,14.066667,92.598045
...,...,...,...,...,...,...,...,...,...,...
2025-12-25,273.302216,485.856323,188.380234,324.561249,117.632187,232.380005,666.361389,313.681671,485.399994,323.206940
2025-12-26,272.892975,485.547729,190.297897,323.318878,117.523659,232.520004,662.108887,313.102478,475.190002,327.400208
2025-12-29,273.252350,484.940430,187.990707,319.217133,118.924744,232.070007,657.517151,313.152405,459.640015,324.548798
2025-12-30,272.573578,485.318756,187.311539,318.891754,119.378616,232.529999,664.764221,313.442017,454.429993,327.725830
2025-12-31,271.355835,481.475861,186.272812,317.708557,118.737274,230.820007,658.914673,312.593109,449.720001,325.703186

#### clean returns

In [28]:
result.clean_returns

,AAPL,MSFT,NVDA,JPM,XOM,AMZN,META,GOOGL,TSLA,UNH
2016-01-05,-0.025379,0.004552,0.015936,0.001727,0.008485,-0.005036,0.004977,0.002748,0.000090,0.001888
2016-01-06,-0.019764,-0.018332,-0.042229,-0.014541,-0.008356,-0.001800,0.002333,-0.002893,-0.019844,-0.010251
2016-01-07,-0.043121,-0.035402,-0.040452,-0.041280,-0.016135,-0.039841,-0.050287,-0.024436,-0.015598,-0.029882
2016-01-08,0.005274,0.003062,-0.021700,-0.022654,-0.020409,-0.001465,-0.006044,-0.013710,-0.021799,-0.017368
2016-01-11,0.016063,-0.000574,0.001686,-0.001529,-0.013479,0.017456,0.001848,0.002951,-0.015041,-0.005279
...,...,...,...,...,...,...,...,...,...,...
2025-12-25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-12-26,-0.001499,-0.000635,0.010128,-0.003835,-0.000923,0.000602,-0.006402,-0.001848,-0.021259,0.012891
2025-12-29,0.001316,-0.001252,-0.012198,-0.012768,0.011851,-0.001937,-0.006959,0.000159,-0.033271,-0.008747
2025-12-30,-0.002487,0.000780,-0.003619,-0.001020,0.003809,0.001980,0.010962,0.000924,-0.011400,0.009741
2025-12-31,-0.004478,-0.007950,-0.005561,-0.003717,-0.005387,-0.007381,-0.008838,-0.002712,-0.010419,-0.006191

#### MetaData on What happened

In [30]:
result.metadata

{'align_dates': True,
 'missing_method': 'ffill_bfill',
 'stale_window': 3,
 'apply_winsorize': False,
 'vol_window': 21,
 'n_assets': 10,
 'n_dates': 2608,
 'return_start': '2016-01-05',
 'return_end': '2025-12-31'}

#### Portfolio weights considered for this run

In [29]:
result.weights

AAPL     0.1
MSFT     0.1
NVDA     0.1
JPM      0.1
XOM      0.1
AMZN     0.1
META     0.1
GOOGL    0.1
TSLA     0.1
UNH      0.1
dtype: float64

#### the portfolio's returns

In [31]:
result.portfolio_returns

2016-01-05    0.000999
2016-01-06   -0.013568
2016-01-07   -0.033643
2016-01-08   -0.011681
2016-01-11    0.000410
                ...
2025-12-25    0.000000
2025-12-26   -0.001278
2025-12-29   -0.006381
2025-12-30    0.000967
2025-12-31   -0.006263
Freq: B, Name: portfolio_returns, Length: 2607, dtype: float64